# Generated by Django 3.1.5 on 2021-04-02 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='.')),
                ('avail', models.BooleanField(default=True)),
                ('served_at', models.CharField(blank=True, choices=[('BR', 'BreakFast'), ('LN', 'Lunch'), ('DI', 'Dinner')], max_length=2)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('NIN', 'North Indian'), ('IT', 'Italian'), ('CHI', 'Chinese'), ('SIN', 'South Indian'), ('KR', 'Korean'), ('SD', 'Side'), ('DES', 'Dessert'), ('BUR', 'Burger'), ('BEV', 'Beverages'), ('SOU', 'Soup'), ('SAL', 'Salad')], default='DEF', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField()),
                ('order_status', models.BooleanField(default=False)),
                ('bill_status', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('items', models.ManyToManyField(related_name='_order_items_+', to='user.Dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaraunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=20)),
                ('takeaway', models.BooleanField(blank=True, default=False)),
                ('payment', models.CharField(choices=[('GPAY', 'Google Pay'), ('UPI', 'UPI PhonePe')], default='Cash', max_length=4)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('cuisine', models.CharField(choices=[('MC', 'MultiCuisine Restaurant'), ('VEG', 'Pure Veg')], default='MC', max_length=4)),
                ('status', models.BooleanField(default=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaraunt', to='user.address')),
                ('combos', models.ManyToManyField(blank=True, related_name='_restaraunt_combos_+', to='user.Dish')),
                ('dishes', models.ManyToManyField(blank=True, related_name='restaraunt', to='user.Dish')),
                ('orders', models.ManyToManyField(blank=True, related_name='restaurant', to='user.Order')),
            ],
        ),
    ]
