# Generated by Django 3.1.5 on 2021-04-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=20)),
                ('takeaway', models.BooleanField(blank=True, default=False)),
                ('payment', models.CharField(choices=[('GPAY', 'Google Pay'), ('UPI', 'UPI PhonePe')], default='Cash', max_length=4)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('cuisine', models.CharField(choices=[('MC', 'MultiCuisine Restaurant'), ('VEG', 'Pure Veg')], default='MC', max_length=4)),
                ('status', models.BooleanField(default=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaraunt', to='user.address')),
                ('combos', models.ManyToManyField(blank=True, related_name='_restaurant_combos_+', to='user.Dish')),
                ('dishes', models.ManyToManyField(blank=True, related_name='restaraunt', to='user.Dish')),
                ('orders', models.ManyToManyField(blank=True, related_name='restaurant', to='user.Order')),
            ],
        ),
        migrations.DeleteModel(
            name='Restaraunt',
        ),
    ]
