# Generated by Django 3.1.5 on 2021-04-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210403_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='avg_time',
            field=models.IntegerField(default=0),
        ),
    ]
