# Generated by Django 3.1.5 on 2021-04-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_order_avg_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_code', models.CharField(max_length=10)),
                ('cust_name', models.CharField(max_length=25)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_status',
            field=models.CharField(choices=[('PD', 'Pending'), ('PD', 'Paid')], default='PD', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CON', 'Confirm')], default='PD', max_length=3),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed')], default='CL', max_length=3),
        ),
    ]
