# Generated by Django 3.1.5 on 2021-04-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210403_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Global',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reservations',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='combos',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='orders',
        ),
        migrations.DeleteModel(
            name='address',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
