# Generated by Django 3.1.5 on 2021-05-02 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='.')),
                ('avail', models.BooleanField(default=True)),
                ('served_at', models.CharField(blank=True, choices=[('BR', 'BreakFast'), ('LN', 'Lunch'), ('DI', 'Dinner')], max_length=2)),
                ('quantity', models.IntegerField(default=1)),
                ('avg_time', models.IntegerField(default=15)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('NIN', 'North Indian'), ('IT', 'Italian'), ('CHI', 'Chinese'), ('SIN', 'South Indian'), ('KR', 'Korean'), ('SD', 'Side'), ('DES', 'Dessert'), ('BUR', 'Burger'), ('BEV', 'Beverages'), ('SOU', 'Soup'), ('SAL', 'Salad')], default='DEF', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(default=1)),
                ('cnf_no', models.IntegerField(default=1)),
                ('rest_no', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('PD', 'Pending'), ('CON', 'Confirm')], default='PD', max_length=3)),
                ('bill_status', models.CharField(choices=[('PD', 'Pending'), ('PD', 'Paid')], default='PD', max_length=3)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('avg_time', models.IntegerField(default=0)),
                ('table_no', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(related_name='_order_items_+', to='hoteladmin.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=20)),
                ('seating_capacity', models.IntegerField(default=50)),
                ('takeaway', models.BooleanField(blank=True, default=False)),
                ('payment', models.CharField(choices=[('UPI', 'UPI PhonePe'), ('CASH', 'Cash Only')], default='Cash', max_length=4)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('cuisine', models.CharField(choices=[('MC', 'MultiCuisine Restaurant'), ('VEG', 'Pure Veg')], default='MC', max_length=4)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed')], default='OP', max_length=3)),
                ('rest_id', models.CharField(default='DEF001', max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaraunt', to='hoteladmin.address')),
                ('combos', models.ManyToManyField(blank=True, related_name='_restaurant_combos_+', to='hoteladmin.Dish')),
                ('dishes', models.ManyToManyField(blank=True, related_name='restaraunt', to='hoteladmin.Dish')),
                ('orders', models.ManyToManyField(blank=True, related_name='_restaurant_orders_+', to='hoteladmin.Order')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_code', models.CharField(max_length=30)),
                ('cust_name', models.CharField(max_length=25)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('CON', 'Confirm')], default='PD', max_length=4)),
                ('tables', models.IntegerField(null=True)),
                ('time', models.TimeField(null=True)),
                ('restaurant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hoteladmin.restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hoteladmin.restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('rest_id',), name='rest_id_constraint'),
        ),
    ]
