# Generated by Django 3.1.5 on 2021-05-02 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0002_auto_20210502_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
