# Generated by Django 3.1.5 on 2021-05-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0003_auto_20210502_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hoteladmin.dish')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='_order_items_+', to='hoteladmin.Item'),
        ),
    ]
