# Generated by Django 3.1.5 on 2021-05-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0006_restaurant_buffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='TimeOut',
            field=models.TimeField(null=True),
        ),
    ]
