# Generated by Django 3.1.5 on 2021-05-05 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0007_reservations_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='reserve_list',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
