# Generated by Django 3.1.5 on 2021-05-05 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0011_auto_20210505_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='reserve_list',
        ),
        migrations.AddField(
            model_name='reservations',
            name='table_no',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.int_list_validator]),
        ),
    ]
