# Generated by Django 3.1.5 on 2021-05-05 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0012_auto_20210505_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='table_no',
            field=models.CharField(default='', max_length=200, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
