# Generated by Django 3.1.5 on 2021-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0014_auto_20210505_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='./user/static/user/media'),
        ),
    ]
