# Generated by Django 3.1.5 on 2021-05-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0019_auto_20210506_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(null=True, related_name='_order_items_+', to='hoteladmin.Item'),
        ),
    ]
