# Generated by Django 3.1.5 on 2021-05-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0020_auto_20210506_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('PD', 'Paid')], default='PEND', max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('CON', 'Confirm')], default='PEND', max_length=4),
        ),
    ]
