# Generated by Django 3.1.5 on 2021-05-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0021_auto_20210506_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('PAID', 'Paid')], default='PEND', max_length=4),
        ),
    ]
