# Generated by Django 3.1.5 on 2021-05-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0022_auto_20210507_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parcel_request',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter_alerted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
