# Generated by Django 3.1.5 on 2021-05-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0023_auto_20210509_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='contact',
            field=models.CharField(default='', max_length=10),
        ),
    ]
